export const featureCardsStyles = {
  container: {
    base: 'py-16 px-4 sm:px-6 lg:px-8',
    wrapper: 'max-w-7xl mx-auto',
  },
  header: {
    container: 'text-center mb-16',
    alignment: 'text-center',
    subtitle: 'text-lg font-medium text-[#03418a] mb-4',
    subtitleDark: 'text-blue-400',
    subtitleLight: 'text-[#03418a]',
    title: 'text-4xl font-bold text-gray-900 mb-6',
    titleDark: 'text-white',
    titleLight: 'text-gray-900',
    description: 'text-xl text-gray-600 max-w-3xl mx-auto',
    descriptionDark: 'text-gray-300',
    descriptionLight: 'text-gray-600',
  },
  common: {
    cards: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8',
    transition: 'transition-all duration-300 ease-in-out',
  },
  card: {
    baseLight: 'bg-white rounded-2xl shadow-lg border border-gray-100 p-8 h-full',
    baseDark: 'bg-gray-800 rounded-2xl shadow-lg border border-gray-700 p-8 h-full',
    hoverLight: 'hover:shadow-xl hover:-translate-y-1',
    hoverDark: 'hover:shadow-xl hover:-translate-y-1',
    content: 'text-center h-full flex flex-col',
    badge: 'inline-block bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1 rounded-full mb-4',
    number: 'text-4xl font-bold text-[#03418a] mb-4',
    image: 'w-16 h-16 mx-auto mb-6 rounded-lg object-cover',
    icon: 'w-16 h-16 mx-auto mb-6 text-[#03418a]',
    iconDark: 'text-blue-400',
    iconLight: 'text-[#03418a]',
    title: 'text-xl font-semibold mb-4',
    titleDark: 'text-white',
    titleLight: 'text-gray-900',
    description: 'text-gray-600 mb-6 flex-grow',
    descriptionDark: 'text-gray-300',
    descriptionLight: 'text-gray-600',
    link: 'inline-flex items-center text-[#03418a] font-medium',
    linkDark: 'text-blue-400',
    linkLight: 'text-[#03418a]',
  },
  backgrounds: {
    white: 'bg-white',
    gray: 'bg-gray-50',
    dark: 'bg-gray-900',
  },
};
