export const accordionStyles = {
  container: {
    base: 'py-16 px-4 sm:px-6 lg:px-8',
    wrapper: 'max-w-4xl mx-auto',
  },
  header: {
    container: 'text-center mb-16',
    alignment: 'text-center',
    subtitle: 'text-lg font-medium text-[#03418a] mb-4',
    subtitleDark: 'text-blue-400',
    subtitleLight: 'text-[#03418a]',
    title: 'text-4xl font-bold text-gray-900 mb-6',
    titleDark: 'text-white',
    titleLight: 'text-gray-900',
    description: 'text-xl text-gray-600 max-w-3xl mx-auto',
    descriptionDark: 'text-gray-300',
    descriptionLight: 'text-gray-600',
  },
  common: {
    items: 'space-y-4',
  },
  item: {
    container: 'border rounded-lg overflow-hidden',
    header: 'w-full px-6 py-4 flex items-center justify-between transition-all duration-300 ease-in-out',
    headerLight: 'bg-white hover:bg-gray-50 border-gray-200',
    headerDark: 'bg-gray-800 hover:bg-gray-700 border-gray-600',
    headerOpen: 'bg-blue-50 border-blue-200',
    number: 'w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-bold mr-4',
    title: 'text-lg font-semibold flex-grow text-left',
    titleDark: 'text-white',
    titleLight: 'text-gray-900',
    badge: 'inline-block bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1 rounded-full mr-4',
    arrow: 'w-5 h-5 text-gray-500 transition-transform duration-300',
    arrowOpen: 'rotate-180',
    content: 'max-h-0 overflow-hidden transition-all duration-300 ease-in-out',
    contentOpen: 'max-h-96',
    contentInner: 'px-6 pb-6',
    image: 'w-16 h-16 rounded-lg object-cover mb-4',
    icon: 'w-16 h-16 text-[#03418a] mb-4',
    iconDark: 'text-blue-400',
    iconLight: 'text-[#03418a]',
    description: 'text-gray-600 mb-4',
    descriptionDark: 'text-gray-300',
    descriptionLight: 'text-gray-600',
    link: 'inline-flex items-center text-[#03418a] font-medium',
    linkDark: 'text-blue-400',
    linkLight: 'text-[#03418a]',
  },
  backgrounds: {
    white: 'bg-white',
    gray: 'bg-gray-50',
    dark: 'bg-gray-900',
  },
};
