import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy | AMC Insured',
  description: 'Global Privacy Policy for AMC Insured',
}

export default function PrivacyPolicyPage() {
  const effectiveDate = 'August 28, 2025'

  return (
    <main
      id='top'
      className='min-h-screen bg-slate-50 text-slate-800 dark:bg-slate-950 dark:text-slate-100'
    >
      {/* Hero */}
      <header className='relative overflow-hidden'>
        <div className='absolute inset-0 -z-10 bg-gradient-to-br from-[#0456b8] via-blue-600 to-sky-500' />
        <div
          aria-hidden
          className='absolute -top-20 right-[-10%] h-72 w-72 rounded-full bg-white/10 blur-3xl'
        />
        <div className='mx-auto max-w-6xl px-6 py-16 md:py-24'>
          <span className='inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-medium text-black ring-1 ring-white/30 backdrop-blur'>
            Privacy
            <span className='h-1 w-1 rounded-full bg-white/60' />
            Global
          </span>
          <h1 className='mt-4 text-4xl font-extrabold leading-tight tracking-tight text-black md:text-5xl lg:text-6xl'>
            Privacy Policy
          </h1>
          <p className='mt-3 text-black'>
            <strong>Effective date:</strong> {effectiveDate}
          </p>

          {/* ▶ Home 버튼 추가 */}
          <div className='mt-6'>
            <Link
              href='/'
              className='inline-flex items-center gap-2 rounded-xl bg-white/90 px-4 py-2 text-slate-900 shadow-sm ring-1 ring-slate-200 backdrop-blur transition hover:bg-white hover:shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-white/60 dark:bg-slate-900/70 dark:text-slate-100 dark:ring-slate-800 dark:focus:ring-offset-slate-950'
            >
              {/* left arrow icon */}
              <svg
                xmlns='http://www.w3.org/2000/svg'
                className='h-4 w-4'
                fill='none'
                viewBox='0 0 24 24'
                stroke='currentColor'
                strokeWidth={2}
              >
                <path
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  d='M10 19l-7-7m0 0l7-7m-7 7h18'
                />
              </svg>
              Back to Home
            </Link>
          </div>
        </div>
      </header>

      {/* Main + TOC */}
      <div className='mx-auto grid max-w-6xl grid-cols-1 gap-8 px-6 py-10 md:py-16 lg:grid-cols-[1fr_320px]'>
        {/* Content */}
        <article className='space-y-10'>
          {/* Callout */}
          <div className='rounded-2xl border border-slate-200/70 bg-white/80 p-5 shadow-sm backdrop-blur dark:border-slate-800 dark:bg-slate-900/60'>
            <p className='text-sm text-slate-600 dark:text-slate-300'>
              This Policy explains how AMC Insured (“we”, “us”, “our”) handles
              personal information when you contact us or use this site. For any
              request, email{' '}
              <a
                href='mailto:info@amcrs.co.kr'
                className='font-medium text-blue-700 underline underline-offset-4 hover:text-blue-800 dark:text-sky-400 dark:hover:text-sky-300'
              >
                info@amcrs.co.kr
              </a>
              .
            </p>
          </div>

          <Section id='collect' title='1) What we collect and how'>
            <ul className='list-disc space-y-1 pl-5'>
              <li>
                <strong>Email inquiries (via “mailto”):</strong> your email
                address, name/signature, any contact details you include, and
                your message/attachments.
              </li>
              <li>
                <strong>Security/operational logs:</strong> IP address,
                user-agent, and timestamp generated by hosting/email systems for
                security and diagnostics.
              </li>
            </ul>
            <Note>
              These items can be personal data/personal information because they
              relate to an identified or identifiable person.
            </Note>
          </Section>

          <Section id='purposes' title='2) Purposes and legal bases'>
            <ul className='list-disc space-y-1 pl-5'>
              <li>
                <strong>Responding to inquiries &amp; records</strong> (GDPR
                Art. 6(1)(b)/(a)).
              </li>
              <li>
                <strong>Security &amp; service integrity</strong> (legitimate
                interests, GDPR Art. 6(1)(f)).
              </li>
            </ul>
            <p className='mt-3'>
              We do <em>not</em> use your information for advertising,
              profiling, or automated decision-making.
            </p>
          </Section>

          <Section id='cookies' title='3) Cookies and tracking'>
            <p>
              We do <strong>not</strong> set non-essential cookies or tracking
              technologies on this site at present. If we later add analytics or
              ads, we will obtain consent where required and provide controls.
            </p>
          </Section>

          <Section id='sharing' title='4) Sharing and processors'>
            <p>
              We do not sell your personal information. We may use service
              providers (e.g., hosting, email, security/anti-abuse tools) that
              process data on our behalf under contracts.
            </p>
          </Section>

          <Section id='transfers' title='5) International transfers'>
            <p>
              Our company and primary systems are located in the Republic of
              Korea. If you are in the EEA/UK and we transfer your data
              internationally, we use appropriate safeguards recognised by law
              (e.g., EU Standard Contractual Clauses or the UK IDTA/Addendum),
              where applicable.
            </p>
          </Section>

          <Section id='retention' title='6) How long we keep information'>
            <ul className='list-disc space-y-1 pl-5'>
              <li>
                <strong>Inquiry emails:</strong> kept only as long as necessary
                for correspondence and our legitimate business/legal needs, then
                securely deleted.
              </li>
              <li>
                <strong>Security logs:</strong> kept for a short, limited period
                for security/diagnostics, then deleted.
              </li>
            </ul>
          </Section>

          <Section id='rights' title='7) Your rights'>
            <p>
              Where applicable law grants you rights (e.g., EEA/UK GDPR), you
              may request access, correction, deletion, restriction,
              portability, or object to certain processing. You also have the
              right to lodge a complaint with your local data protection
              authority. For California residents (if and to the extent the
              CCPA/CPRA applies): rights to know/delete/correct and to opt-out
              of “sale” or “sharing” (we do not sell or share), without
              discrimination.
            </p>
          </Section>

          <Section id='children' title='8) Children’s privacy'>
            <p>
              Our site is intended for business audiences and not for children.
            </p>
          </Section>

          <Section id='security' title='9) Security'>
            <p>
              We use reasonable technical and organisational measures (transport
              encryption, access controls, logging) to protect information.
            </p>
          </Section>

          <Section id='changes' title='10) Changes'>
            <p>
              We may update this Policy from time to time. We will post updates
              on this page with a new effective date.
            </p>
            <div className='mt-4 flex items-center justify-between rounded-xl border border-slate-200 bg-white p-3 text-sm shadow-sm dark:border-slate-800 dark:bg-slate-900/60'>
              <span className='text-slate-600 dark:text-slate-300'>
                Effective date: <strong>{effectiveDate}</strong>
              </span>
              <a
                href='#top'
                className='rounded-lg px-3 py-1.5 text-slate-600 underline underline-offset-4 hover:text-slate-900 dark:text-slate-300 dark:hover:text-white'
              >
                Back to top
              </a>
            </div>
          </Section>
        </article>

        {/* TOC */}
        <aside className='lg:sticky lg:top-20'>
          <nav
            aria-label='Table of contents'
            className='rounded-2xl border border-slate-200/70 bg-white/80 p-5 shadow-sm backdrop-blur dark:border-slate-800 dark:bg-slate-900/60'
          >
            <p className='mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400'>
              On this page
            </p>
            <ul className='space-y-2 text-sm'>
              {[
                ['collect', 'What we collect'],
                ['purposes', 'Purposes & legal bases'],
                ['cookies', 'Cookies and tracking'],
                ['sharing', 'Sharing and processors'],
                ['transfers', 'International transfers'],
                ['retention', 'How long we keep info'],
                ['rights', 'Your rights'],
                ['children', 'Children’s privacy'],
                ['security', 'Security'],
                ['changes', 'Changes'],
              ].map(([id, label]) => (
                <li key={id}>
                  <a
                    href={`#${id}`}
                    className='group inline-flex items-center gap-2 rounded-lg px-2 py-1 text-slate-700 hover:bg-slate-100 hover:text-slate-900 dark:text-slate-300 dark:hover:bg-slate-800 dark:hover:text-white'
                  >
                    <span className='h-1.5 w-1.5 rounded-full bg-slate-300 transition group-hover:bg-blue-500 dark:bg-slate-600 dark:group-hover:bg-sky-400' />
                    {label}
                  </a>
                </li>
              ))}
            </ul>

            {/* ▶ 사이드에도 Home 버튼(선택) */}
            <div className='mt-4 pt-4 border-t border-slate-200 dark:border-slate-800'>
              <Link
                href='/'
                className='inline-flex w-full items-center justify-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-sm font-medium text-white shadow hover:brightness-110 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-900/50 dark:bg-slate-800 dark:focus:ring-offset-slate-900'
              >
                Home
              </Link>
            </div>
          </nav>
        </aside>
      </div>
    </main>
  )
}

/* ---------- Small presentational helpers ---------- */
function Section({
  id,
  title,
  children,
}: {
  id: string
  title: string
  children: React.ReactNode
}) {
  return (
    <section id={id} className='scroll-mt-24'>
      <h2 className='mb-3 text-2xl font-bold tracking-tight text-slate-900 dark:text-white'>
        {title}
      </h2>
      <div className='space-y-3 leading-relaxed text-slate-700 dark:text-slate-300'>
        {children}
      </div>
    </section>
  )
}

function Note({ children }: { children: React.ReactNode }) {
  return (
    <div className='mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900 dark:border-amber-900/40 dark:bg-amber-900/20 dark:text-amber-100'>
      <p className='text-sm'>{children}</p>
    </div>
  )
}
