export const processFlowStyles = {
  container: {
    base: 'py-16 px-4 sm:px-6 lg:px-8',
    wrapper: 'max-w-7xl mx-auto',
  },
  header: {
    container: 'text-center mb-16',
    alignment: 'text-center',
    subtitle: 'text-lg font-medium text-[#03418a] mb-4',
    subtitleDark: 'text-blue-400',
    subtitleLight: 'text-[#03418a]',
    title: 'text-4xl font-bold text-gray-900 mb-6',
    titleDark: 'text-white',
    titleLight: 'text-gray-900',
    description: 'text-xl text-gray-600 max-w-3xl mx-auto',
    descriptionDark: 'text-gray-300',
    descriptionLight: 'text-gray-600',
  },
  common: {
    flow: 'flex flex-col lg:flex-row items-center justify-between gap-8 lg:gap-4',
    transition: 'transition-all duration-300 ease-in-out',
  },
  step: {
    circleLight: 'w-20 h-20 bg-blue-600 rounded-full flex items-center justify-center shadow-lg',
    circleDark: 'w-20 h-20 bg-blue-500 rounded-full flex items-center justify-center shadow-lg',
    number: 'text-2xl font-bold text-white',
    content: 'text-center mt-6 max-w-xs',
    contentLight: 'text-gray-900',
    contentDark: 'text-white',
    badge: 'inline-block bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1 rounded-full mb-3',
    title: 'text-lg font-semibold mb-3',
    titleDark: 'text-white',
    titleLight: 'text-gray-900',
    description: 'text-gray-600 text-sm mb-4',
    descriptionDark: 'text-gray-300',
    descriptionLight: 'text-gray-600',
    link: 'inline-flex items-center text-[#03418a] font-medium text-sm',
    linkDark: 'text-blue-400',
    linkLight: 'text-[#03418a]',
  },
  connector: {
    line: 'hidden lg:block w-24 h-0.5 relative',
    lineLight: 'bg-blue-300',
    lineDark: 'bg-blue-600',
    arrow: 'absolute right-0 top-1/2 transform -translate-y-1/2 w-0 h-0 border-l-8 border-l-blue-300 border-t-4 border-t-transparent border-b-4 border-b-transparent',
  },
  backgrounds: {
    white: 'bg-white',
    gray: 'bg-gray-50',
    dark: 'bg-gray-900',
  },
};
